Yep
parmanchaddha/rank_this_song pull request #5
Opened 2020-07-20 23:23 UTC by natekred

dude its a masterpiece

2020-07-20 23:40 UTC, parmanchaddha requested changes
Can you please start making the changes in the 4 smaller files, while I look at the large 5th file. Atleast, the 5th file doesn't seem so bad right now.

2020-07-20 23:40 UTC, parmanchaddha commented on rank_this_song/rank_this_song/src/index.js
> +import './song_shit.css';
NO! This should be imported in the file with the same name. See BandFormStepper.js. 

- [ ] Change import of song_shit.css to song_shit.js
- [ ] While you are doing that, rename song_shit.js to the actual name of the component.

2020-07-20 23:40 UTC, parmanchaddha commented on rank_this_song/rank_this_song/src/BandFormStepper.js
> +  export function StepContent(props) {
This is a react component not a javascript function. This should NOT be exported. Why are you exporting it? 

-[ ] Do not export React components unless it's a default export.

2020-07-20 23:40 UTC, parmanchaddha commented on rank_this_song/rank_this_song/src/BandFormStepper.js
> +         songfunc(song_list)
Nope songfunc SHOULD NOT be a function. It should be a react component with hooks. 
Therefore, the syntax I am expecting here is 
`<SongFunc 
        band_name={band_name}  
        song_list = {song_list}
/>`

2020-07-20 23:40 UTC, parmanchaddha commented on rank_this_song/rank_this_song/src/BandFormStepper.js
> +export function CustomizedSteppers() {
Again, this SHOULD be a default export since this is the stepper file. Please change this back to being a DEFAULT export.

2020-07-20 23:40 UTC, parmanchaddha commented on rank_this_song/rank_this_song/src/song_shit.css
> +.container2{
AUTOMATIC FAIL:
 
css classtitles need to be specific so that when I am looking at the css file I know where the styling is applied.

2020-07-20 23:40 UTC, parmanchaddha commented on rank_this_song/rank_this_song/src/song_shit.css
> +.container2{
Change literally every single class title.

2020-07-20 23:40 UTC, parmanchaddha commented on rank_this_song/rank_this_song/src/song_shit.css
> +.container2{
I am actually not even going to read this until the changes are made cuz wtf even knows whats going on.

2020-07-20 23:40 UTC, parmanchaddha commented on rank_this_song/rank_this_song/src/song_shit.js
> +import React from "react";
Will have to download and run this file on my own computer to see what's going on here.

2020-07-21 02:04 UTC, natekred commented on rank_this_song/rank_this_song/src/song_shit.css
> +.container2{
what do you mean by specific

2021-07-09 14:58 UTC, closed without merging